service: monday-aws-integration

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: Allow
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"
    - Effect: Allow
      Action: lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action: events:*
      Resource: "*"
    - Effect: Allow
      Action: cloudwatch:*
      Resource: "*"

functions:
  hello:
    handler: src/handlers.hello
    events:
        - http:
            method: POST
            path: "event_push"
            cors: true
  iamhere:
    handler: src/handlers.iamhere
    events:
      - eventBridge:
          eventBus: custombus
          pattern:
            source:
              - hello.iamhere.cb

